version: "2.2"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_DB: '${PG_DATABASE}'
    env_file: '.env'
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data:z
    healthcheck:
      test: 'pg_isready -U postgres'
      interval: 5s
      timeout: 10s
      retries: 12
  
